server:
  port: 8091
  servlet:
    context-path: /

# 整合spring数据源
spring:
  datasource:
    # 引入druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jtdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: 123456

  # 配置mvc的页面 注意层级结构对应关系
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp

# 整合mybatis或者mybatis-plus,只有名称改变,里面具体配置完全一致
mybatis-plus:
  # 配置别名包
  type-aliases-package: com.github.gudian1618.pojo
  # 配置mapper映射文件
#  mapper-locations: classpath:/mybatis/mappers/*.xml
  # 开启驼峰映射规则,则可以自动的实现对象的赋值
  configuration:
    map-underscore-to-camel-case: true

# 添加日志输出
logging:
  level:
    com.github.gudian1618.springbootmybatis: debug

